CREATE TABLE CATEGORY(
	X_CAT	 		NUMBER(5),
	NAME			VARCHAR2(50) UNIQUE,
	ID_FOURSQUARE	VARCHAR2(30) UNIQUE NOT NULL
);

ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (X_CAT);


CREATE TABLE CATEGORY_SUB(
	X_SUBC 			NUMBER(5),
	NAME			VARCHAR2(50) UNIQUE,
	ID_FOURSQUARE	VARCHAR2(30) UNIQUE NOT NULL,
	CAT_X_CAT		NUMBER(5)
);

ALTER TABLE CATEGORY_SUB ADD CONSTRAINT PK_SUB_CATEGORY PRIMARY KEY (X_SUBC);


CREATE TABLE USER_NORMAL (
	X_USER			NUMBER(5),
	NAME			VARCHAR2(16) UNIQUE NOT NULL,
	PASSWORD		VARCHAR2(16) NOT NULL,
	EMAIL			VARCHAR2(30) NOT NULL,
	CREATION_DATE	DATE,
	TOKEN			VARCHAR2(50)
);

ALTER TABLE USER_NORMAL ADD CONSTRAINT PK_USER_NORMAL PRIMARY KEY (X_USER);


CREATE TABLE PLACE (
	X_PLACE			NUMBER(5),
	NAME			VARCHAR2(50),
	LAT				NUMBER(4,10),
	LNG 			NUMBER(4,10),
	ADDRESS			VARCHAR2(30),
	CC				VARCHAR2(10),
	CITY			VARCHAR2(30),
	COUNTRY			VARCHAR2(30),
	POSTAL_CODE		VARCHAR2(16),
	PROVINCE		VARCHAR2(30),
	EMAIL			VARCHAR2(30),
	FACEBOOK		VARCHAR2(50),
	PHONE			VARCHAR2(16),
	TWITTER			VARCHAR2(50),
	ID_FOURSQUARE	VARCHAR2(30) UNIQUE NOT NULL,
	VERIFIED		NUMBER(1),
	SUBC_X_SUBC		NUMBER(5)
);

ALTER TABLE PLACE ADD CONSTRAINT PK_PLACE PRIMARY KEY (X_PLACE);


CREATE TABLE PLACE_COMMENT (
	X_COMM			NUMBER(5),
	TITLE			VARCHAR2(20) NOT NULL, 
	BODY			VARCHAR2(300) NOT NULL,
	STATE			VARCHAR2(10) NOT NULL,
	REASON			VARCHAR2(100),
	USER_X_USER		NUMBER(5),
	PLACE_X_PLACE	NUMBER(5)
); 

ALTER TABLE PLACE_COMMENT ADD CONSTRAINT PK_PLACE_COMMENT PRIMARY KEY (X_COMM);


CREATE TABLE ROUTE (
	X_ROUTE			NUMBER(5),
	STATE			VARCHAR2(12),
	NUM_PLACES		NUMBER(2),
	CITY			VARCHAR2(30),
	DISTANCE		NUMBER(8),
	TIME			NUMBER(20),
	USER_X_USER 	NUMBER(5)
);

ALTER TABLE ROUTE ADD CONSTRAINT PK_ROUTE PRIMARY KEY (X_ROUTE);


CREATE TABLE ROUTE_PLACE (
	X_RP			NUMBER(5),
	ROUTE_X_ROUTE	NUMBER(5),
	PLACE_X_PLACE	NUMBER(5),
	ORDER_  		NUMBER(2),
	DISTANCE		NUMBER(8),
	TIME_			NUMBER(20),
	TRAVEL_MODE		VARCHAR2(12)
);

ALTER TABLE ROUTE_PLACE ADD CONSTRAINT PK_ROUTE_PLACE PRIMARY KEY (X_RP);


CREATE TABLE USER_PLACE (
	X_UP			NUMBER(5),
	USER_X_USER		NUMBER(5),
	PLACE_X_PLACE	NUMBER(5),
	STATE			VARCHAR2(16),
	CITY			VARCHAR2(30)
);

ALTER TABLE USER_PLACE ADD CONSTRAINT PK_USER_PLACE PRIMARY KEY (X_UP);


