DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE CATEGORY_SUB CASCADE CONSTRAINTS;
DROP TABLE USER_ CASCADE CONSTRAINTS;
DROP TABLE PLACE CASCADE CONSTRAINTS;
DROP TABLE ROUTE CASCADE CONSTRAINTS;
DROP TABLE ROUTE_DAY CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE EVENT_DAY CASCADE CONSTRAINTS;
DROP TABLE EVENT_PLACE CASCADE CONSTRAINTS;
DROP TABLE STAY CASCADE CONSTRAINTS;



DROP SEQUENCE CATEGORY_SEQ;

DROP SEQUENCE CATEGORY_SUB_SEQ;

DROP SEQUENCE PLACE_SEQ;

DROP SEQUENCE ROUTE_SEQ;

DROP SEQUENCE STAY_SEQ;

DROP SEQUENCE USER_SEQ;

DROP SEQUENCE EVENT_SEQ;

DROP SEQUENCE EVENT_PLACE_SEQ;