DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE CATEGORY_SUB CASCADE CONSTRAINTS;
DROP TABLE USER_NORMAL CASCADE CONSTRAINTS;
DROP TABLE PLACE CASCADE CONSTRAINTS;
DROP TABLE PLACE_COMMENT CASCADE CONSTRAINTS;
DROP TABLE ROUTE CASCADE CONSTRAINTS;
DROP TABLE ROUTE_PLACE CASCADE CONSTRAINTS;
DROP TABLE USER_PLACE CASCADE CONSTRAINTS;