
CREATE SEQUENCE CATEGORY_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE SEQUENCE CATEGORY_SUB_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE SEQUENCE EVENT_PLACE_SEQ START WITH 8 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 10;

CREATE SEQUENCE EVENT_SEQ START WITH 3 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 10;

CREATE SEQUENCE PLACE_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 10;

CREATE SEQUENCE ROUTE_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 10;

CREATE SEQUENCE STAY_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 10;

CREATE SEQUENCE USER_SEQ START WITH 3 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 10;
