CREATE OR REPLACE TRIGGER TRIGGER1 
AFTER INSERT ON ROUTE_PLACE
REFERENCING NEW AS nuevo
FOR EACH ROW
DECLARE
pragma autonomous_transaction;
BEGIN
  UPDATE ROUTE SET NUM_PLACES = NUM_PLACES + 1 WHERE ROUTE.X_ROUTE = :nuevo.ROUTE_X_ROUTE;
  COMMIT;
END;