CREATE OR REPLACE TRIGGER ROUTE_NUM_DAYS_ADD
AFTER INSERT ON DAY
REFERENCING NEW AS nuevo
FOR EACH ROW
DECLARE
pragma autonomous_transaction;
BEGIN
  UPDATE ROUTE SET NUM_DAYS = NUM_DAYS + 1 WHERE ROUTE.X_ROUTE = :nuevo.ROUTE_X_ROUTE;
  COMMIT;
END;


CREATE OR REPLACE TRIGGER ROUTE_NUM_DAYS_DELETE
AFTER DELETE ON DAY
REFERENCING OLD AS viejo
FOR EACH ROW
DECLARE
pragma autonomous_transaction;
BEGIN
  UPDATE ROUTE SET NUM_DAYS = NUM_DAYS - 1 WHERE ROUTE.X_ROUTE = :viejo.ROUTE_X_ROUTE;
  COMMIT;
END;