CREATE OR REPLACE TRIGGER ROUTE_NUM_DAYS_ADD
AFTER INSERT ON ROUTE_DAY
REFERENCING NEW AS nuevo
FOR EACH ROW
DECLARE
pragma autonomous_transaction;
BEGIN
  UPDATE ROUTE SET NUM_DAYS = NUM_DAYS + 1 WHERE ROUTE.X_ROUTE = :nuevo.ROUTE_X_ROUTE;
  COMMIT;
END;


CREATE OR REPLACE TRIGGER ROUTE_NUM_DAYS_DELETE
AFTER DELETE ON ROUTE_DAY
REFERENCING OLD AS viejo
FOR EACH ROW
DECLARE
pragma autonomous_transaction;
BEGIN
  UPDATE ROUTE SET NUM_DAYS = NUM_DAYS - 1 WHERE ROUTE.X_ROUTE = :viejo.ROUTE_X_ROUTE;
  COMMIT;
END;


CREATE OR REPLACE TRIGGER ROUTE_DERIVED_TIME
AFTER INSERT OR DELETE OR UPDATE OF TRAVEL_TIME ON STAY
BEGIN
  UPDATE ROUTE SET TIME = (SELECT SUM(TRAVEL_TIME) FROM STAY WHERE STAY.ROUTE_X_ROUTE = ROUTE.X_ROUTE);
END;

CREATE OR REPLACE TRIGGER ROUTE_DERIVED_DISTANCE
AFTER INSERT OR DELETE OR UPDATE OF TRAVEL_DISTANCE ON STAY
BEGIN
  UPDATE ROUTE SET DISTANCE = (SELECT SUM(TRAVEL_DISTANCE) FROM STAY WHERE STAY.ROUTE_X_ROUTE = ROUTE.X_ROUTE);
END;

CREATE OR REPLACE TRIGGER ROUTE_DERIVED_NUMPLACES
AFTER INSERT OR DELETE ON STAY
BEGIN
  UPDATE ROUTE SET NUM_PLACES = (SELECT COUNT(*) FROM STAY WHERE STAY.ROUTE_X_ROUTE = ROUTE.X_ROUTE);
END;